
# Spring Shutdown Control
server:
  servlet:
    context-path: /utils   # Consolidate(??)
  shutdown: graceful

banner:
  location: classpath:banner.txt

# Jasypt ???? ?
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: jasyptKey!@3$

spring:
  application:
    name: module-utils  # ?????? ?? (Config Server?? ? ???? ??? ??)
  profiles:
    active: default

# ?? ?? ??
logging:
  level:
    root: INFO   # Map Type ??
