
server:
  servlet:
    context-path: /utils   # Consolidate(??)

spring:
  application:
    name: module-utils  # ?????? ?? (Config Server?? ? ???? ??? ??)
  config:
    #    import: optional:configserver:http://localhost:8888/conf   # optional: Config Server?? ??? ?????, ?? ??? ??? ???? ?? ??
    import: optional:configserver:http://conf.fado.kr/conf   # ?? Config ???? ????
  profiles:
    active: default